"""
SQLAlchemy database models for the Intelligent Web Data Aggregator.

This module defines the database schema using SQLAlchemy ORM models.
These models represent the persistent data structures for tasks and cached parsers.
"""

from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean, JSON, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from datetime import datetime
from typing import Optional, Dict, Any

from .database import Base


class ScrapingTask(Base):
    """
    Model for storing scraping task information and status.
    
    This table tracks all scraping requests, their status, and results.
    Each task represents a user request to scrape data from a specific URL
    with a natural language prompt.
    """
    
    __tablename__ = "scraping_tasks"
    
    # Primary key
    id = Column(Integer, primary_key=True, index=True)
    
    # Task identification
    task_id = Column(String(255), unique=True, index=True, nullable=False)
    
    # Request data
    url = Column(Text, nullable=False)
    user_prompt = Column(Text, nullable=False)
    
    # Task status and metadata
    status = Column(String(50), nullable=False, default="PENDING")  # PENDING, IN_PROGRESS, SUCCESS, FAILED
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    started_at = Column(DateTime(timezone=True), nullable=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)
    
    # Error handling
    error_message = Column(Text, nullable=True)
    retry_count = Column(Integer, default=0, nullable=False)
    
    # Results
    extracted_data = Column(JSON, nullable=True)  # Final extracted data as JSON
    total_matches = Column(Integer, nullable=True)  # Number of matches found
    
    # Processing metadata
    processing_time_seconds = Column(Integer, nullable=True)
    used_cached_parser = Column(Boolean, default=False, nullable=False)
    
    # Source data captured during scraping
    page_content = Column(Text, nullable=True)  # Raw page content (innerText)
    network_requests = Column(JSON, nullable=True)  # Captured network requests

    # Intent & source mapping (added migration 0002)
    intent_target = Column(Text, nullable=True)
    intent_keywords = Column(JSON, nullable=True)
    chosen_source_url = Column(Text, nullable=True)
    chosen_source_type = Column(String(50), nullable=True)
    
    # Relationships
    used_parser_id = Column(Integer, ForeignKey("parsers_cache.id"), nullable=True)
    used_parser = relationship("ParserCache", back_populates="tasks")
    
    def __repr__(self) -> str:
        return f"<ScrapingTask(id={self.id}, task_id='{self.task_id}', status='{self.status}')>"


class ParserCache(Base):
    """
    Model for caching successful regex parsers.
    
    This table stores validated regular expressions that have been successfully
    generated by the LLM and tested against real data. These cached parsers
    can be reused for similar requests to avoid redundant LLM API calls.
    """
    
    __tablename__ = "parsers_cache"
    
    # Primary key
    id = Column(Integer, primary_key=True, index=True)
    
    # URL pattern matching
    url_pattern = Column(String(500), nullable=False, index=True)  # Pattern or exact URL
    domain = Column(String(255), nullable=False, index=True)  # Extracted domain for faster lookups
    
    # User intent matching
    user_intent = Column(Text, nullable=False)  # Normalized/processed user prompt
    intent_keywords = Column(JSON, nullable=True)  # Extracted keywords for matching
    target_data_type = Column(String(100), nullable=True)  # e.g., "job_listings", "product_prices"
    
    # Parser information
    generated_regex = Column(Text, nullable=False)  # The working regular expression
    source_type = Column(String(50), nullable=False)  # 'HTML', 'JSON', 'XML', etc.
    source_identifier = Column(Text, nullable=True)  # URL of XHR request or selector for HTML
    
    # Validation and performance
    test_matches_count = Column(Integer, nullable=False)  # Number of matches during validation
    confidence_score = Column(Integer, default=100, nullable=False)  # 0-100, decreases with failed reuses
    success_rate = Column(Integer, default=100, nullable=False)  # Percentage of successful reuses
    times_used = Column(Integer, default=0, nullable=False)  # How many times this parser was reused
    
    # Metadata
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    last_used_at = Column(DateTime(timezone=True), nullable=True)
    created_by_task_id = Column(String(255), nullable=False)  # Task that created this parser
    
    # LLM generation context
    llm_model_used = Column(String(100), nullable=True)  # e.g., "gpt-4", "claude-3"
    generation_attempts = Column(Integer, default=1, nullable=False)  # How many attempts to generate
    
    # Sample data for validation
    sample_input = Column(Text, nullable=True)  # Sample of the source content used for generation
    sample_output = Column(JSON, nullable=True)  # Sample of expected extraction results
    
    # Relationships
    tasks = relationship("ScrapingTask", back_populates="used_parser")
    
    def __repr__(self) -> str:
        return f"<ParserCache(id={self.id}, domain='{self.domain}', target='{self.target_data_type}')>"
