name: Deploy to Google Cloud

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCE_INSTANCE: diploma-backend
  GCE_ZONE: europe-west1-b

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Compute Engine
        run: |
          gcloud compute ssh dada_marchan@$GCE_INSTANCE --zone=$GCE_ZONE --tunnel-through-iap --command="
            cd ~/diploma && 
            git pull origin master &&
            sudo docker compose up -d --build --remove-orphans
          "
